services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "9258:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:9147
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "9147:8000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    environment:
      - DATABASE_URL=sqlite:///./foster_dogs.db
      - SECRET_KEY=your-secret-key-change-in-production
      - CORS_ORIGINS=http://localhost:9258
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  frontend_node_modules: